### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by aLIEzsss4** [ant-design/ant-motion#133]
ReferenceError
document is not defined
ReferenceError: document is not defined
    at checkStyleName (H:\dbv1.1.16\node_modules\_style-utils@0.1.13@style-utils\main.js:144:30)
    at new Element (H:\dbv1.1.16\node_modules\_rc-banner-anim@1.0.0@rc-banner-anim\lib\Element.js:236:54)
    at H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:292:18
    at measureLifeCyclePerf (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:291:16)
    at ReactCompositeComponentWrapper._constructComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:282:19)
    at ReactCompositeComponentWrapper.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:185:21)
    at Object.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactDOMComponent.js:657:32)
    at ReactDOMComponent.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactDOMComponent.js:524:29)
    at Object.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:368:34)
    at ReactCompositeComponentWrapper.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:255:21)
    at Object.mountComponent (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (H:\dbv1.1.16\node_modules\_react-dom@15.6.2@react-dom\lib\ReactMultiChild.js:234:44)

**Comment by jljsj33** [comment]
什么环境的？？服务端？？？

**Comment by jljsj33** [comment]
删了重装下。。。
