### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'E:\react\ant-motion-master\_site\exhibition\demo\:contentName.html'

### ISSUE THREAD

**Issue by camnpr** [ant-design/ant-motion#181]
[2] Created:  _site\templates\index.html
[2] Created:  _site\templates\404.html
[2] bisheng build -c ./src/bisheng.templates.config.js exited with code 0
[1] Created:  _site\edit\index.html
[1] Created:  _site\edit\404.html
[1] bisheng build -c ./src/bisheng.edit.config.js exited with code 0
[0] Created:  _site\index.html
[0] Created:  _site\exhibition\.html
[0] fs.js:646
[0]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[0]                  ^
[0]
[0] Error: ENOENT: no such file or directory, open 'E:\react\ant-motion-master\_site\exhibition\demo\:contentName.html'
[0]     at Object.fs.openSync (fs.js:646:18)
[0]     at Object.fs.writeFileSync (fs.js:1299:33)
[0]     at E:\react\ant-motion-master\node_modules\_bisheng@0.26.0@bisheng\lib\index.js:154:12
[0]     at Array.forEach (<anonymous>)
[0]     at E:\react\ant-motion-master\node_modules\_bisheng@0.26.0@bisheng\lib\index.js:151:24
[0]     at Compiler.<anonymous> (E:\react\ant-motion-master\node_modules\_webpack@1.12.15@webpack\lib\Compiler.js:194:14)
[0]     at Compiler.emitRecords (E:\react\ant-motion-master\node_modules\_webpack@1.12.15@webpack\lib\Compiler.js:282:37)
[0]     at Compiler.<anonymous> (E:\react\ant-motion-master\node_modules\_webpack@1.12.15@webpack\lib\Compiler.js:187:11)
[0]     at E:\react\ant-motion-master\node_modules\_webpack@1.12.15@webpack\lib\Compiler.js:275:11
[0]     at Compiler.applyPluginsAsync (E:\react\ant-motion-master\node_modules\_tapable@0.1.10@tapable\lib\Tapable.js:60:69)
[0] bisheng build -c ./src/bisheng.index.config.js exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-motion@1.6.1 site: `concurrently "bisheng build -c ./src/bisheng.index.config.js" "bisheng build -c ./src/bisheng.edit.config.js" "bisheng build -c ./src/bisheng.templates.config.js"`
npm ERR! Exit status 1

`cnpm install && cnpm run site`

> exhibition:
[0]    { demo:
[0]       { carousel3d: 'exhibition\\demo\\carousel3d.md',
[0]         'detail-switch': 'exhibition\\demo\\detail-switch.md',
[0]         'list-anim': 'exhibition\\demo\\list-anim.md',
[0]         'list-sort': 'exhibition\\demo\\list-sort.md',
[0]         'logo-gather-anim': 'exhibition\\demo\\logo-gather-anim.md',
[0]         'pic-details-anim': 'exhibition\\demo\\pic-details-anim.md',
[0]         snow: 'exhibition\\demo\\snow.md',
[0]         'table-enter-leave': 'exhibition\\demo\\table-enter-leave.md' } } }

>  [ '/index.html',
[0]   '\\exhibition\\.html',
[0]   '\\exhibition\\demo\\:contentName.html',

**Comment by jljsj33** [comment]
Ant motion 网站没升bisheng 不支持windos。。。
